function waypoint = waypoint()
%WAYPOINT This funtion returns a waypoint struct
waypoint   = struct('time_along_traj', 0, ...
                        'curvature', 0, ...
                        'arclength', 0, ...
                        'velocity', 0, ...
                        'position', [0, 0], ...
                        'lateral_bounds', [1, -1], ...
                        'velocity_bounds', [0, 20]);
end

